apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer-pod
spec:
  containers:
  - name: kafka-consumer-container
    image: cglvodoi97/kafka-consumer:withcustomer
    imagePullPolicy: Always
    ports:
    - containerPort: 9092
    resources:
      limits:
        cpu: "0.5"
        memory: "0.5Gi"
      requests:
        cpu: "0.5"
        memory: "0.5Gi"
    volumeMounts:
    - name: config-volume
      mountPath: /app/client.properties
      subPath: client.properties
  volumes:
  - name: config-volume
    configMap:
      name: kafka-consumer-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer-config
data:
  client.properties: |
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
    security.protocol=SASL_SSL
    sasl.mechanisms=PLAIN
    sasl.username=CRWLWGMCXLBJGX74
    sasl.password=WgKQebqREVoTQOjlXIAKEbHYdfy2ktyaVTc6v1tloRVZBOriyDrrvVNOd99V3W0W

    # Best practice for higher availability in librdkafka clients prior to 1.7
    session.timeout.ms=45000
